# Generated by Django 5.1.6 on 2025-03-17 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuser',
            name='Customer',
        ),
        migrations.AddField(
            model_name='medicine',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cuser'),
        ),
    ]
